services:

  web:
    build: .
    command: >
      sh -c "export MQTT_AUTOSTART=1 &&
             cd CONTROL_HELADERAS &&
             python manage.py migrate --noinput &&
             daphne -b 0.0.0.0 -p 8000 ERROR_PROOFING.asgi:application"
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/CONTROL_HELADERAS
    environment:
      - DJANGO_SETTINGS_MODULE=ERROR_PROOFING.settings
      - MQTT_AUTOSTART=1

volumes:
  sqlite_data:
