# Generated by Django 6.0.4 on 2026-04-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('sensor_id', models.CharField(default='sensor_01', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Temperatura',
                'verbose_name_plural': 'Temperaturas',
                'ordering': ['-timestamp'],
            },
        ),
    ]
