# Generated by Django 6.0.4 on 2026-04-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DASHBOARD_TEMP_VOLT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voltaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('sensor_id', models.CharField(default='voltaje_01', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Voltaje',
                'verbose_name_plural': 'Voltajes',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelTable(
            name='temperatura',
            table='DASHBOARD_TEMP_VOLT_temperatura',
        ),
    ]
